### ISSUE TITLE
Need to update all comments to use proper Docstring syntax

### ISSUE THREAD

**Issue by anthonyLuttrell** [anthonyLuttrell/RedditStatsBot#10]
https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings

**Comment by sushpawar001** [comment]
Hello, I can do this. Can you please assign this issue to me?

**Comment by anthonyLuttrell** [comment]
Hi, are you from Reddit? 

Please start from the dev or dev_oop branch, I've already made some changes there.

**Comment by sushpawar001** [comment]
No, Not from Reddit. Thanks.

**Comment by anthonyLuttrell** [comment]
Okay, no problem. I had invited some other people to work on things, so I wasn't sure. Feel free to contribute as much as you want. 

I am still working on organizing everything, the branches are a mess right now, so I apologize.
